// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../src/plugins');
config.visualization.decoratorPaths.push(__dirname + '/../src/decorators');

config.seedProjects.enable = true
config.seedProjects.basePaths = ['seeds']
config.visualization.svgDirs.push(__dirname + '/../assets/LogicGateSVGs/');


config.seedProjects.defaultProject = 'LogicGates'


// Visualizer descriptors

// Add requirejs paths
config.requirejsPaths = {
  'webgme-logic-gates': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/webgme_logic_gates';
validateConfig(config);
module.exports = config;
